language: android
jdk: oraclejdk8

env:
  global:
    - ANDROID_API=28
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-${ANDROID_API}
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.+


deploy:
  provider: releases
  github-token: d3748eb233c70834e1dd5d8b7082af1b25a1d295
 # file_glob: true
 $ file: /home/travis/build/TravisCliExample/app/build/outputs/apk/release/*
 # local_dir: build
  on:
#    repo: IniyanApp/traviscliexample
  branch: master
    tags: true

